"""empty message

Revision ID: c350f119be85
Revises: 329f853af775
Create Date: 2025-02-23 22:42:17.580064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c350f119be85'
down_revision = '329f853af775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.alter_column('translation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('translation_language',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.alter_column('translation_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('translation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
